config/routes.rb
Rails.application.routes.draw do

root 'lines#index'

resources :lines, only: [:index, :show]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lines_controller.rb
class LinesController < ApplicationController

  before_action :import_csv, only: [:index, :show]

  def index
    @search_results = {}
    @file.each do |k,v|
      if k == params[:keywords].to_i
        @search_results[k]=v
      elsif params[:keywords].nil?
        @search_results = nil
      end
    end
  end

  def show
    @line = @file[params[:id].to_i]
    if @line.present?
      @status = "202"
      render :status => 202
    else
      @status = "413"
      render :status => 413
    end
  end

  private

  def import_csv
    @file = {}
    line = 0
    @test = File.foreach(ENV["FILE_TO_SERVE"]).map { |line| line.split('\n') }
    @test[0].each do |x|
      @file[line+=1]=x
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LineServer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/lines/index.html.erb
<%= form_tag lines_path, method: :get do %>
<table align="center" width="500px" border=1 cellpadding=4>
    <tr>
      <td><%= text_field_tag :keywords, params[:keywords], size: 75 %></td>
    </tr>
    <tr>
      <td><%= submit_tag "Search", name: nil %></td>
    </tr>
</table>
<% end %>

<% if @search_results.present? %>
  <% @search_results.each do |k,v| %>
    <p><%=link_to k,line_path(k)%> - <%=link_to v, line_path(k)%></p>
  <% end %>
<% else %>
  <p> No Lines Retured </p>
<% end %>

app/views/lines/show.html.erb
<p>Status Code: <%= @status %></p>
<% if @line.present? %>
  <p><%= @line %></p>
<% end %>